name: aircon
channels:
- conda-forge
dependencies:
- geopandas
- openeo
- pyarrow
- pykrige
- rasterio
- rioxarray
- scikit-gstat
- scikit-learn
- xarray
- jupyterlab # Added for running Jupyter notebooks
- pandas
- numpy
- matplotlib
- pyproj
- tqdm
- ipykernel
- seaborn
